name: Testchain
on: [push]

jobs:
  amd64:
    name: Testchain
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push master-cosmos-validator-node
        run: docker buildx build --tag leeway321/cosmos-master-node --file deploy/testchain/mainNode/cosmos/Dockerfile --platform linux/amd64 --push --progress tty --build-arg PUBLIC_IP=${{ secrets.MASTER_NODE_HOST }} --build-arg GIT_HUB_USER=sunnyk56 --build-arg GIT_HUB_PASS=Leeway321 --build-arg GIT_HUB_EMAIL=sunnyk@leewayhertz.com --build-arg GIT_HUB_BRANCH=ONET-65 --build-arg GIT_HUB_REPO=https://github.com/sunnyk56/market.git .

      - name: start master-cosmos-validator-node
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run hello-world && docker rm -f $(docker ps -a -q) && docker rmi -f $(docker images -q) && docker run --name master_cosmos_validator_node -d -p 26656:26656 -p 26657:26657 -p 1317:1317 -p 9090:9090 leeway321/cosmos-master-node /bin/sh -c "sleep infinity | /root/scripts/init.sh"
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: Build and push peer-cosmos-validator-node
        run: docker buildx build --tag leeway321/cosmos-peer-node --file deploy/testchain/peerNode/cosmos/Dockerfile --platform linux/amd64 --push --progress tty --build-arg PUBLIC_IP=${{ secrets.PEER_NODE_HOST }} --build-arg GIT_HUB_USER=sunnyk56 --build-arg GIT_HUB_PASS=Leeway321 --build-arg GIT_HUB_EMAIL=sunnyk@leewayhertz.com --build-arg GIT_HUB_BRANCH=ONET-65 --build-arg GIT_HUB_REPO=https://github.com/sunnyk56/market.git .
      - name: start peer-cosmos-validator-node
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run hello-world && docker rm -f $(docker ps -a -q) && docker rmi -f $(docker images -q) && docker run --name peer-cosmos-validator-node -d -p 26656:26656 -p 26657:26657 -p 1317:1317 -p 9090:9090 leeway321/cosmos-peer-node /bin/sh -c "sleep infinity | /root/scripts/init.sh"
          host: ${{ secrets.PEER_NODE_HOST }}
          username: root
          password: ""
          privateKey: ${{ secrets.PRIVATE_KEY}}
